-- FILENAME: CGD/Axioms/Ontology.lean

import CGD.Axioms.Spacetime
import CGD.Foundations.GaugeGroup
import CGD.Foundations.Calculus
import Mathlib.Analysis.Calculus.ContDiff.Basic

namespace CGD.Axioms

open CGD.Foundations

/-- 
A smooth, anti-Hermitian SU(2) gauge field. 
(As an abstract Lie algebra, it possesses no spacetime chirality).
-/
structure Su2GaugeField where
  val : Fin 4 → CGD.Axioms.SpacetimePoint → SL2C
  is_smooth : ∀ mu i j, ContDiff ℝ ⊤ (fun x => (val mu x).val i j)
  is_su2 : ∀ mu x, isSu2 (val mu x).val

instance : CoeFun Su2GaugeField (fun _ => Fin 4 → CGD.Axioms.SpacetimePoint → SL2C) where
  coe := Su2GaugeField.val

instance : Zero Su2GaugeField where
  zero := {
    val := fun _ _ => 0
    is_smooth := fun _ _ _ => contDiff_const
    is_su2 := fun _ _ => by
      constructor
      · change Matrix.trace (0 : Matrix (Fin 2) (Fin 2) ℂ) = 0
        simp
      · change Matrix.conjTranspose (0 : Matrix (Fin 2) (Fin 2) ℂ) = -(0 : Matrix (Fin 2) (Fin 2) ℂ)
        ext i j
        simp
  }

/-- 
The Core Ontology: The Universe is a macroscopic Spin(4, C) connection.
By the canonical isomorphism 𝔰p𝔦n(4, ℂ) ≅ 𝔰𝔩(2, ℂ)_SD ⊕ 𝔰𝔩(2, ℂ)_ASD, 
the full 4D spacetime geometry is generated by two independent SU(2) chiral sectors.
-/
structure Universe where
  sd_sector : Su2GaugeField
  asd_sector : Su2GaugeField

instance : Zero Universe where
  zero := { sd_sector := 0, asd_sector := 0 }

/-- 
The Spin(4, C) 4x4 Dirac Representation.
This definition mathematically enforces the spacetime chirality of the Universe. 
The sd_sector is strictly embedded as the Self-Dual (+1) eigenspace of γ5 (top-left), 
and the asd_sector is strictly embedded as the Anti-Self-Dual (-1) eigenspace (bottom-right).
-/
noncomputable def Universe.spin4c_connection (u : Universe) (mu : Fin 4) (x : CGD.Axioms.SpacetimePoint) : ChiralM := 
  embedSelfDual (u.sd_sector mu x) + embedAntiSelfDual (u.asd_sector mu x)

end CGD.Axioms
