-- FILENAME: CGD/Quantum/Measurement/Ensemble.lean

import Litlib.Core
import CGD.Axioms.Ontology
import CGD.Foundations.GaugeGroup
import CGD.Foundations.Hamiltonian
import Litlib.Y2007.dittrich2007partial.Signature
import Litlib.Y1989.arnold1989mathematical.Chapter03.Sec16_Liouville
import Mathlib.MeasureTheory.Measure.MeasureSpaceDef
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic

open scoped BigOperators
open Litlib.Y2007.dittrich2007partial
open Litlib.Y1989.arnold1989mathematical

namespace CGD.Quantum.Measurement

/-- 
A macroscopic preparation of a topological state.
Because macroscopic equipment can only orient the 3D spatial geometry (the S² base 
of the SU(2) Hopf Fibration) and cannot restrict the internal U(1) relative phase, 
the state is physically prepared as a uniform ensemble over the U(1) fiber.
-/
structure MacroscopicPreparation where
  boundary : CGD.Foundations.BoundarySurface
  -- The target geometric orientation (the S² base of the SU(2) group)
  theta : ℝ
  phi : ℝ
  -- The internal relative U(1) phase is physically unconstrained
  is_unconstrained_phase : True

/--
Proves that the U(1) relative phase between the boundary of a prepared state and 
a detector acts as a rigorous gauge-invariant relational observable (a partial clock), 
completely isolating the boundary dynamics from the frozen 3D bulk.
-/
theorem u1FiberIsRelationalObservable
  (boundary : CGD.Foundations.BoundarySurface)
  (α : (Fin 1 → ℝ) → CGD.Axioms.Sl2cGaugeField → CGD.Axioms.Sl2cGaugeField)
  (f : CGD.Axioms.Sl2cGaugeField → ℝ)
  (T : Fin 1 → CGD.Axioms.Sl2cGaugeField → ℝ)
  (F : (Fin 1 → ℝ) → CGD.Axioms.Sl2cGaugeField → ℝ)
  (h_flow : CGD.Foundations.isBoundaryFlow α boundary)
  (h_clock : ∀ i, CGD.Foundations.isBoundaryObservable (T i) boundary)
  (h_obs : CGD.Foundations.isBoundaryObservable f boundary)
  (dittrich : Theorem4_1 1 α f T F) :
  (∀ τ A B, (∃ β, ∀ i, T i (α β A) = τ i) → CGD.Foundations.agreesOnBoundary A B boundary → F τ A = F τ B) ∧
  (∀ τ x ε, (∃ β, ∀ i, T i (α β x) = τ i) → F τ (α ε x) = F τ x) := by
  exact CGD.Foundations.emergentRelationalDynamics 1 boundary α f T F h_flow h_clock h_obs dittrich

/--
Proves that when the boundary gauge flow is generated by a divergence-free vector field 
(such as the phase-translation operator along the U(1) fiber), the continuous gauge 
transformations strictly preserve the finite-dimensional volume measure of the ensemble.
This guarantees that an initially uniform ensemble over the Hopf fiber remains uniform.
-/
theorem finiteLiouvilleBoundaryFlow
  (n : ℕ)
  [ms : MeasureTheory.MeasureSpace (Fin n → ℝ)]
  (f : (Fin n → ℝ) → (Fin n → ℝ))
  (g : ℝ → (Fin n → ℝ) → (Fin n → ℝ))
  [liouville : LiouvilleTheoremND (n := n)]
  (h_flow_gen : ∀ t x i, deriv (fun t' => g t' x i) t = f (g t x) i)
  (h_group_id : ∀ x, g 0 x = x)
  (h_group_add : ∀ t₁ t₂ x, g (t₁ + t₂) x = g t₁ (g t₂ x))
  (h_div_free : ∀ x, (∑ i : Fin n, deriv (fun y => f (Function.update x i y) i) (x i)) = 0)
  (h_f_diff : ∀ x i j, Differentiable ℝ (fun y => f (Function.update x j y) i))
  (h_g_diff : ∀ x i, Differentiable ℝ (fun t => g t x i)) :
  ∀ t s, @MeasurableSet (Fin n → ℝ) ms.toMeasurableSpace s → MeasureTheory.volume (g t '' s) = MeasureTheory.volume s := by
  intros t s hs
  -- We apply the theorem; t and s are automatically unified, leaving exactly 7 subgoals
  apply LiouvilleTheoremND.preserves_volume f g
  · exact h_f_diff
  · exact h_g_diff
  · exact h_group_id
  · exact h_group_add
  · exact h_flow_gen
  · exact h_div_free
  · exact hs

end CGD.Quantum.Measurement
