-- FILENAME: CGD/Quantum/Vacuum.lean

import Litlib.Core
import CGD.Foundations.Calculus
import CGD.Gravity.Geometry
import CGD.Axioms.Ontology
import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.Analysis.Calculus.FDeriv.Add

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

open CGD.Foundations CGD.Gravity CGD.Axioms Matrix Complex

namespace CGD.Quantum

lemma project_zero (a : Fin 3) (mu nu : Fin 4) :
  project (fun _ _ => (0 : SL2C)) a mu nu = 0 := by
  unfold project
  change 0.5 * Matrix.trace ((0 : SL2C).val * (getPauli a).val) = 0
  have h_zero_val : (0 : SL2C).val = 0 := rfl
  rw[h_zero_val]
  simp

lemma urbantkeMetric_zero :
  urbantkeMetric (fun _ _ => (0 : SL2C)) = 0 := by
  ext mu nu
  unfold urbantkeMetric
  simp_rw [project_zero]
  simp

lemma partialDerivMat_zero (idx : Fin 4) (x : SpacetimePoint) :
  partialDerivMat idx (fun _ => (0 : SL2C).val) x = 0 := by
  ext i j
  unfold partialDerivMat partialDeriv
  have h_zero : (fun (p : SpacetimePoint) => (0 : SL2C).val i j) = Function.const SpacetimePoint (0 : ℂ) := rfl
  rw [h_zero]
  rw [fderiv_const]
  rfl

lemma partialDerivSl2c_zero (idx : Fin 4) (x : SpacetimePoint) :
  partialDerivSl2c idx (fun _ => (0 : SL2C)) x = 0 := by
  unfold partialDerivSl2c
  change toSl2c (partialDerivMat idx (fun _ => (0 : SL2C).val) x) = 0
  rw[partialDerivMat_zero idx x]
  ext i j
  unfold toSl2c
  simp

lemma curvatureSl2c_zero (mu nu : Fin 4) (x : SpacetimePoint) :
  curvatureSl2c (fun _ _ => (0 : SL2C)) mu nu x = 0 := by
  unfold curvatureSl2c
  change partialDerivSl2c mu (fun _ => (0 : SL2C)) x - partialDerivSl2c nu (fun _ => (0 : SL2C)) x + ⁅(0 : SL2C), (0 : SL2C)⁆ = 0
  rw[partialDerivSl2c_zero mu x, partialDerivSl2c_zero nu x]
  simp

/--
🟢 PRIORITY TARGET: Spacetime Vacuum Condensate.
ALGEBRAIC CONTEXT: This is a direct proof by contrapositive: if A = 0, then F = 0, which yields g = 0, meaning det(g) = 0.
PHYSICAL SIGNIFICANCE: In pure connection emergent gravity, spacetime volume is not a fixed background; it is dynamically generated by the gauge field. Therefore, the existence of macroscopic space (det g ≠ 0) strictly mathematically forbids the trivial vacuum (A = 0). Spacetime itself requires a non-zero gauge condensate.
-/
theorem kinematicVacuumCondensate (u : Universe) (x : SpacetimePoint) :
  (urbantkeMetric (fun mu nu => curvatureSl2c u.light mu nu x)).det ≠ 0 →
  u.light.val ≠ (fun _ _ => 0) := by
  intro h_det h_trivial
  apply h_det
  rw [h_trivial]
  have h_curv : (fun mu nu => curvatureSl2c (fun _ _ => (0 : SL2C)) mu nu x) = (fun _ _ => (0 : SL2C)) := by 
    ext mu nu
    rw [curvatureSl2c_zero]
  rw[h_curv]
  rw[urbantkeMetric_zero]
  exact Matrix.det_zero ⟨0⟩

end CGD.Quantum
